insert into county(name, state) values('Los Angeles', 'CA');
insert into county(name, state) values('San Diego', 'CA');
insert into county(name, state) values('Orange', 'CA');
insert into county(name, state) values('Riverside', 'CA');
insert into county(name, state) values('San Bernardino', 'CA');
insert into county(name, state) values('Santa Clara', 'CA');
insert into county(name, state) values('Alameda', 'CA');
insert into county(name, state) values('Sacramento', 'CA');
insert into county(name, state) values('Contra Costa', 'CA');
insert into county(name, state) values('Fresno', 'CA');
insert into county(name, state) values('Kern', 'CA');
insert into county(name, state) values('San Francisco', 'CA');
insert into county(name, state) values('Ventura', 'CA');
insert into county(name, state) values('San Joaquin', 'CA');
insert into county(name, state) values('San Mateo', 'CA');
insert into county(name, state) values('Stanislaus', 'CA');
insert into county(name, state) values('Sonoma', 'CA');
insert into county(name, state) values('Tulare', 'CA');
insert into county(name, state) values('Solano', 'CA');
insert into county(name, state) values('Santa Barbara', 'CA');
insert into county(name, state) values('Monterey', 'CA');
insert into county(name, state) values('Placer', 'CA');
insert into county(name, state) values('San Luis Obispo', 'CA');
insert into county(name, state) values('Merced', 'CA');
insert into county(name, state) values('Santa Cruz', 'CA');
insert into county(name, state) values('Marin', 'CA');
insert into county(name, state) values('Butte', 'CA');
insert into county(name, state) values('Yolo', 'CA');
insert into county(name, state) values('El Dorado', 'CA');
insert into county(name, state) values('Shasta', 'CA');
insert into county(name, state) values('Imperial', 'CA');
insert into county(name, state) values('Madera', 'CA');
insert into county(name, state) values('Kings', 'CA');
insert into county(name, state) values('Napa', 'CA');
insert into county(name, state) values('Humboldt', 'CA');
insert into county(name, state) values('Nevada', 'CA');
insert into county(name, state) values('Sutter', 'CA');
insert into county(name, state) values('Mendocino', 'CA');
insert into county(name, state) values('Yuba', 'CA');
insert into county(name, state) values('Lake', 'CA');
insert into county(name, state) values('Tehama', 'CA');
insert into county(name, state) values('San Benito', 'CA');
insert into county(name, state) values('Tuolumne', 'CA');
insert into county(name, state) values('Calaveras', 'CA');
insert into county(name, state) values('Siskiyou', 'CA');
insert into county(name, state) values('Amador', 'CA');
insert into county(name, state) values('Lassen', 'CA');
insert into county(name, state) values('Glenn', 'CA');
insert into county(name, state) values('Del Norte', 'CA');
insert into county(name, state) values('Colusa', 'CA');
insert into county(name, state) values('Plumas', 'CA');
insert into county(name, state) values('Inyo', 'CA');
insert into county(name, state) values('Mariposa', 'CA');
insert into county(name, state) values('Trinity', 'CA');
insert into county(name, state) values('Mono', 'CA');
insert into county(name, state) values('Modoc', 'CA');
insert into county(name, state) values('Sierra', 'CA');
insert into county(name, state) values('Alpine', 'CA');
