INSERT INTO county(name, state) VALUES
('Accomack', 'VA'),
('Albemarle', 'VA'),
('Alleghany', 'VA'),
('Amelia', 'VA'),
('Amelia', 'VA'),
('Amherst', 'VA'),
('Appomattox', 'VA'),
('Arlington', 'VA'),
('Augusta', 'VA'),
('Bath', 'VA'),
('Bedford', 'VA'),
('Bland', 'VA'),
('Botetourt', 'VA'),
('Brunswick', 'VA'),
('Buchanan', 'VA'),
('Buckingham', 'VA'),
('Campbell', 'VA'),
('Caroline', 'VA'),
('Carroll', 'VA'),
('Charles City', 'VA'),
('Charlotte', 'VA'),
('Chesterfield', 'VA'),
('Clarke', 'VA'),
('Craig', 'VA'),
('Culpeper', 'VA'),
('Cumberland', 'VA'),
('Dickenson', 'VA'),
('Dinwiddie', 'VA'),
('Essex', 'VA'),
('Fairfax', 'VA'),
('Fauquier', 'VA'),
('Floyd', 'VA'),
('Fluvanna', 'VA'),
('Franklin', 'VA'),
('Frederick', 'VA'),
('Giles', 'VA'),
('Gloucester', 'VA'),
('Goochland', 'VA'),
('Grayson', 'VA'),
('Greene', 'VA'),
('Greensville', 'VA'),
('Halifax', 'VA'),
('Hanover', 'VA'),
('Henrico', 'VA'),
('Henry', 'VA'),
('Highland', 'VA'),
('Isle of Wight', 'VA'),
('James City', 'VA'),
('King and Queen', 'VA'),
('King George', 'VA'),
('King William', 'VA'),
('Lancaster', 'VA'),
('Lee', 'VA'),
('Loudoun', 'VA'),
('Louisa', 'VA'),
('Lunenburg', 'VA'),
('Madison', 'VA'),
('Mathews', 'VA'),
('Mecklenburg', 'VA'),
('Middlesex', 'VA'),
('Montgomery', 'VA'),
('Nelson', 'VA'),
('New Kent', 'VA'),
('Northampton', 'VA'),
('Northumberland', 'VA'),
('Nottoway', 'VA'),
('Orange', 'VA'),
('Page', 'VA'),
('Patrick', 'VA'),
('Pittsylvania', 'VA'),
('Powhatan', 'VA'),
('Prince Edward', 'VA'),
('Prince George', 'VA'),
('Prince William', 'VA'),
('Pulaski', 'VA'),
('Rappahannock', 'VA'),
('Richmond', 'VA'),
('Roanoke', 'VA'),
('Rockbridge', 'VA'),
('Rockingham', 'VA'),
('Russell', 'VA'),
('Scott', 'VA'),
('Shenandoah', 'VA'),
('Smyth', 'VA'),
('Southampton', 'VA'),
('Spotsylvania', 'VA'),
('Stafford', 'VA'),
('Surry', 'VA'),
('Sussex', 'VA'),
('Tazewell', 'VA'),
('Warren', 'VA'),
('Washington', 'VA'),
('Westmoreland', 'VA'),
('Wise', 'VA'),
('Wythe', 'VA'),
('York', 'VA'),
('Alexandria City', 'VA'),
('Bristol City', 'VA'),
('Buena Vista City', 'VA'),
('Charlottesville City', 'VA'),
('Chesapeake City', 'VA'),
('Colonial Heights City', 'VA'),
('Covington City', 'VA'),
('Danville City', 'VA'),
('Emporia City', 'VA'),
('Fairfax City', 'VA'),
('Falls Church City', 'VA'),
('Franklin City', 'VA'),
('Fredericksburg City', 'VA'),
('Galax City', 'VA'),
('Hampton City', 'VA'),
('Harrisonburg City', 'VA'),
('Hopewell City', 'VA'),
('Lexington City', 'VA'),
('Lynchburg City', 'VA'),
('Manassas City', 'VA'),
('Manassas Park City', 'VA'),
('Martinsville City', 'VA'),
('Newport News City', 'VA'),
('Norfolk City', 'VA'),
('Norton City', 'VA'),
('Petersburg City', 'VA'),
('Poquoson City', 'VA'),
('Portsmouth City', 'VA'),
('Radford City', 'VA'),
('Richmond City', 'VA'),
('Roanoke City', 'VA'),
('Salem City', 'VA'),
('Staunton City', 'VA'),
('Suffolk City', 'VA'),
('Virginia Beach City', 'VA'),
('Waynesboro City', 'VA'),
('Williamsburg City', 'VA'),
('Winchester City', 'VA') ON CONFLICT DO NOTHING;